language: node_js
node_js:
  - 0.10
before_script:
  - npm install jshint
  - npm install bower
  - bower install
script:
  npm run lint && npm test
email:
  on_failure: change
  on_success: never
cache:
  directories:
    - node_modules